import Head from 'next/head';
import Link from 'next/link';
import { useQuery } from 'urql';
import { PRODUCT_QUERY} from "../lib/query";

export default function Home() {
  
  const [results] = useQuery({query: PRODUCT_QUERY});
  const {data, fetching, error} = results;
  console.log(results);

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Next</h1>
        <Link href={'/about'}>about</Link>
      </main>

     
    </div>
  )
}
