import Head from 'next/head';
import Link from 'next/link';
import { useQuery } from 'urql';
import { PRODUCT_QUERY} from "../lib/query";
import Products from "../components/Products";
import { Gallery } from '../styles/gallery';

export default function Home() {

  const [results] = useQuery({query: PRODUCT_QUERY});
  const {data, fetching, error} = results;

  if (fetching) return <p>Loading</p>
  if (error) return <p>Error ... {error.message}</p>
  const products = data.produits.data;


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Next</h1>
        <Gallery>
          {products.map((produits)=>(
            <Products key ={produits.key} produits = {produits}/>
          ))}
        </Gallery>
      </main>  
    </>
  )
}
